### PR TITLE
Update Debian packaging for latest libkqueue

### PR DESCRIPTION
**Pull request by mcnewton**
Works with the master branch, so will need a new libkqueue release.

### CODE REVIEW

**Comment by mheily** [comment]
Thanks Matthew! I'll upload this to https://mentors.debian.net and request a new sponsor to get it uploaded to Debian from there.

**Comment by mcnewton** [comment]
That would be great, thanks! Will need to cut a 2.3.1 release that includes the recent commits to libkqueue as well.

**Comment by mheily** [comment]
Ok, I tagged a v2.3.1 release. Would you mind updating your PR to build
against this version, and do a quick sanity check to make sure the package
builds/works for you?

**Comment by mcnewton** [comment]
Thanks! Tested and had a couple of small issues - can you merge the libkqueue PR which bumps the version number, and then re-release that as v2.3.1? There's no changes apart from the version number and changelog.

Then the PR on the debian package updates to patch against the new version number, and I found a missing "include" for the static library build (it doesn't show up when you build with the library already on the system...). I fixed a couple of lintian warnings, too.

Then I think it's good to go.

**Comment by mheily** [comment]
Take a look at this PR for the main kqueue repo:

https://github.com/mheily/libkqueue/pull/56

This should eliminate the need to mantain a Debian-specific patch.

Thanks,

 - Mark

**Pull request merged**
